# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
